### ISSUE TITLE
language alteration needed in bucket creation exercise.

### ISSUE THREAD

**Issue by jvntra** [learn-co-curriculum/dsc-set-up-aws-iam#4]
## Link to Canvas

https://my.learn.co/courses/756/pages/m1-dot-aws-access-keys-boto3-and-making-buckets?module_item_id=98819

## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x] Instructions unclear
- [ ] Other (explain below)

### Source

```
import boto3

s3 = boto3.resource('s3')

s3.create_bucket(Bucket='Test Bucket')

```

### Concern

1.) AWS bucket names can consist only of lowercase letters, numbers, dots, and hyphens. The indication here will raise an exception. 

2.) Also the presumable remedy to this is for students to then enter the name as `test-bucket` however this will also raise an exception because a bucket of the same name likely already exists. 

## (Optional) Proposed Solution

1.) Include the above information in the markdown to alert students to the use of appropriate characters.

2.) Add language to customize the test bucket name with numbers or random terms (i.e.  ...Bucket='test-bucket-<random_number_or_word>'

## What OS Are You Using?

- [x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [x] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for pointing this out. I have updated the readme.
